---

- name: Docker old version deletion
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-engine
    - docker
    - docker-common
    - docker.io

- name:  Add Docker GPG key
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: Docker repository add
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Docker install
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Verification docker enabled and started
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

