---
- name: Make sure epel is installed
  yum:
    name: epel-release
    state: "{{ epel_package_state }}"

- name: Make sure hashicorp repo is added
  yum_repository:
    name: hashicorp
    description: hashicorp repository
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Download and install Consul
  yum:
    name: consul
    state: "{{ consul_package_state }}"
  notify: restart consul

- name: Create consul config files
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: "consul"
    group: "consul"
    mode: 0664
  notify: restart consul

- name: Make sure that Consul is running and enabled on boot
  service: 
    name: "consul" 
    state: "{{ consul_service_state }}"
    enabled: "{{ consul_service_enabled }}"
      