---

- name: GET raw nomad job file from Github /alertmanager.nomad
  get_url:
    url: "{{ alert_url }}"
    dest: /alertmanager.nomad
- name: Create dir for alertmanager config file
  file:
    path: /opt/alertmanager
    state: directory
    mode: '0777'

- name: Get alerts.yml 
  template:
    src: alerts.yml.j2
    dest: /opt/alertmanager/alerts.yml

- name: Validate nomad job file syntax /alertmanager.nomad
  shell: nomad job validate /alertmanager.nomad

- name: Run nomad job file /alertmanager.nomad
  shell: nomad job run /alertmanager.nomad
